# Generated by Django 5.1 on 2024-11-03 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                ("cat_id", models.AutoField(primary_key=True, serialize=False)),
                ("cat_name", models.CharField(max_length=50)),
                ("cat_name_en", models.CharField(max_length=50)),
                (
                    "cat_image",
                    models.ImageField(upload_to="images/categories/%y/%m/%d"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("pr_id", models.AutoField(primary_key=True, serialize=False)),
                ("pr_name", models.CharField(max_length=50)),
                ("pr_name_en", models.CharField(max_length=50)),
                ("pr_image", models.ImageField(upload_to="images/product/%y/%m/%d")),
                ("pr_cost", models.IntegerField()),
                ("pr_detail", models.CharField(max_length=150)),
                ("pr_detail_en", models.CharField(max_length=150)),
                (
                    "cat_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="pages.categories",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                ("fav_no", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pr_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.product"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField()),
                (
                    "user_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pr_fk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pages.product"
                    ),
                ),
            ],
        ),
    ]
