# Generated by Django 5.1 on 2024-11-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="co_expiredate",
            field=models.DateField(),
        ),
    ]
