# Generated by Django 5.1 on 2024-10-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_delete_categoriesqww"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="cat_image",
            field=models.ImageField(upload_to="images/categories/%y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pr_image",
            field=models.ImageField(upload_to="images/product/%y/%m/%d"),
        ),
    ]
