# Generated by Django 5.1 on 2024-11-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co', models.CharField(max_length=50)),
                ('co_count', models.IntegerField()),
                ('co_discount', models.IntegerField()),
                ('co_expiredate', models.DateTimeField()),
            ],
        ),
    ]
